apiVersion: v1
kind: Service
metadata:
  name: evm-mcp-service
  namespace: evm-mcp-server
  labels:
    app: evm-mcp-server
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: evm-mcp-server